  mongoCliente:
    image: mongo
    restart: always
    hostname: mongodb
    command: mongod --port 8081
    ports:
      - 8081:8081

  java8Cliente:
    image: shinyay/docker-mvn-jdk8:3.5.0
    ports:
    - "8086:8086"
    volumes:
    - ".:/usr/src/myapp"
    working_dir: /usr/src/myapp
    command: >
        bash -c "mvn clean test
        && cd target
        && java -jar filmes-0.0.1-SNAPSHOT.jar"
    links:
    - mongoCliente
    
